apiVersion: v1 
kind: Service
metadata:
  name: event-demo-ui-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: event-demo-ui
  type: LoadBalancer
