apiVersion: apps/v1 
kind: Deployment
metadata:
  name: event-demo-ui
spec: 
  selector:
    matchLabels:
      app: event-demo-ui
  replicas: 2 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: event-demo-ui
    spec:
      containers:
      - name: event-demo-ui
        image: gcr.io/dtc082021-222/event-external:1.0.1
        env: 
        - name: SERVER
          value: "http://event-demo-service:8082"
        ports:
        - containerPort: 8080
            
        